name: Callable Test

  
on:
    pull_request:
    push:
        branches:
            - '[0-9]+.[0-9]+'
            - 'main'

jobs:
    test:
        name: "PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.2'
                      dependency-versions: 'highest'

                    - php-version: '8.3'
                      dependency-versions: 'highest'

        steps:
            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'
                  ini-values: memory_limit=-1
                  coverage: none

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}

            - name: Run tests
              run: vendor/bin/phpunit
